In [1]:
import numpy as np

In [3]:
i = [1,2,3,4,5,6]

i

[1, 2, 3, 4, 5, 6]

In [5]:
np.array(i)

array([1, 2, 3, 4, 5, 6])

In [6]:
j = [[1,2,3],[4,5,6],[7,8,9]]

j

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(j)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
import numpy as np

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,18,3)

array([ 1,  4,  7, 10, 13, 16])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [27]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [28]:
np.linspace(1,50,80)

array([ 1.        ,  1.62025316,  2.24050633,  2.86075949,  3.48101266,
        4.10126582,  4.72151899,  5.34177215,  5.96202532,  6.58227848,
        7.20253165,  7.82278481,  8.44303797,  9.06329114,  9.6835443 ,
       10.30379747, 10.92405063, 11.5443038 , 12.16455696, 12.78481013,
       13.40506329, 14.02531646, 14.64556962, 15.26582278, 15.88607595,
       16.50632911, 17.12658228, 17.74683544, 18.36708861, 18.98734177,
       19.60759494, 20.2278481 , 20.84810127, 21.46835443, 22.08860759,
       22.70886076, 23.32911392, 23.94936709, 24.56962025, 25.18987342,
       25.81012658, 26.43037975, 27.05063291, 27.67088608, 28.29113924,
       28.91139241, 29.53164557, 30.15189873, 30.7721519 , 31.39240506,
       32.01265823, 32.63291139, 33.25316456, 33.87341772, 34.49367089,
       35.11392405, 35.73417722, 36.35443038, 36.97468354, 37.59493671,
       38.21518987, 38.83544304, 39.4556962 , 40.07594937, 40.69620253,
       41.3164557 , 41.93670886, 42.55696203, 43.17721519, 43.79

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
np.random.rand(2)

array([0.90311679, 0.9867017 ])

In [36]:
np.random.rand(8,5)

array([[0.37136697, 0.71295954, 0.16161978, 0.89920176, 0.37819209],
       [0.76626624, 0.11502888, 0.37214003, 0.52375338, 0.6902202 ],
       [0.65556884, 0.75013683, 0.12471112, 0.57699076, 0.66266667],
       [0.18046575, 0.66595413, 0.12255996, 0.30340462, 0.49130904],
       [0.5421518 , 0.9152156 , 0.07942822, 0.84001747, 0.98712598],
       [0.8557282 , 0.92647285, 0.62195244, 0.93528687, 0.62680969],
       [0.25460969, 0.95152317, 0.70537565, 0.3349931 , 0.66217603],
       [0.45057141, 0.16172164, 0.83422022, 0.41865271, 0.80653509]])

In [37]:
np.random.randn(3)

array([-0.24722889, -0.99697235,  1.39988462])

In [38]:
np.random.randn(5)

array([ 1.35699809,  0.57218596, -1.27519051,  1.13226434,  0.32310223])

In [39]:
np.random.randn(9)

array([ 1.47923035,  0.19437838,  0.83918123, -0.35869414, -0.43835465,
       -0.28207772,  0.75527302, -1.13984558, -1.03044946])

In [40]:
np.random.randn(6,6)

array([[ 0.36904083,  0.41815979,  0.78415874, -0.7065942 , -0.81906717,
         0.54879621],
       [-0.50349987, -0.5625998 ,  0.67612751, -0.06421567,  0.72894725,
        -0.90131989],
       [-0.19849637, -1.81467884,  1.52611062,  1.75325995, -0.30132313,
        -0.18027422],
       [ 0.16082873, -0.98182137,  0.47239708, -0.89176254,  0.46479584,
        -1.24957808],
       [-0.82793764, -1.74208169,  0.871452  ,  0.47348256,  0.55860699,
         0.00345744],
       [-0.29770321, -0.96257449, -1.17452263,  2.08675619, -0.04413432,
         0.13832801]])

In [53]:
np.random.randint(5)

1

In [57]:
np.random.randint(2,8)

7

In [58]:
np.random.randint(10,70,12)

array([17, 19, 40, 40, 66, 14, 27, 30, 51, 55, 35, 10])

In [66]:
i = np.arange(15)

j = np.random.randint(0,15,10)



In [62]:
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
j

array([ 0,  7,  8,  8, 13,  3,  6,  3,  2,  1])

In [79]:
j.reshape(2,5)

array([[ 0,  7,  8,  8, 13],
       [ 3,  6,  3,  2,  1]])

In [83]:
k = np.array([1,2,3,4,5,6,7,8])

k.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
m = np.array([1,2,3,9,4,6,7,8,9])

m.reshape(3,3)

array([[1, 2, 3],
       [9, 4, 6],
       [7, 8, 9]])

In [88]:
m

array([1, 2, 3, 9, 4, 6, 7, 8, 9])

In [89]:
m.max()

9

In [90]:
m.min()

1

In [93]:
m = np.array([1,2,3,9,4,6,7,8,9,0])

m.argmax()

3

In [94]:
m.argmin()

9

In [95]:
m.shape

(10,)

In [97]:
m.reshape(2,5)

array([[1, 2, 3, 9, 4],
       [6, 7, 8, 9, 0]])

In [98]:
m.reshape(2,5).shape

(2, 5)

In [99]:
m.reshape(5,2)

array([[1, 2],
       [3, 9],
       [4, 6],
       [7, 8],
       [9, 0]])

In [103]:
m.reshape(1,10)

array([[1, 2, 3, 9, 4, 6, 7, 8, 9, 0]])

In [104]:
m.reshape(10,1)

array([[1],
       [2],
       [3],
       [9],
       [4],
       [6],
       [7],
       [8],
       [9],
       [0]])

In [105]:
m.dtype

dtype('int32')